// The contract between the app and parentveda.in, tested against the strings
// the website ACTUALLY produces.
//
// Every referrer literal below was generated by running the real
// carePlayStoreUrl() / playStoreUrl() from C:\parentveda-web\src\lib\ and
// reading the `referrer` parameter back out. Google Play hands the app the
// decoded value, which is what these are.
//
// This is the seam where a silent failure lives: nothing on either side throws
// if they drift, the app just quietly credits nobody — or worse, the wrong
// person. Two repos, one contract, one test.

import 'package:flutter_test/flutter_test.dart';
import 'package:parentveda/care_partner/care_partner_engine.dart';
import 'package:parentveda/care_partner/care_partner_models.dart';
import 'package:parentveda/referral/install_referrer.dart';
import 'package:parentveda/referral/referral_engine.dart';

void main() {
  group('care referrers, exactly as the website emits them', () {
    const withChannel =
        'utm_source=care&utm_medium=partner&utm_content=KM7QX2PDVR&utm_term=qr';
    const withCampaign = 'utm_source=care&utm_medium=partner'
        '&utm_content=KM7QX2PDVR&utm_term=whatsapp&utm_campaign=diwali';
    const bare = 'utm_source=care&utm_medium=partner&utm_content=KM7QX2PDVR';

    test('the token comes through', () {
      for (final r in [withChannel, withCampaign, bare]) {
        expect(InstallReferrerService.partnerTokenFromReferrer(r), 'KM7QX2PDVR',
            reason: r);
      }
    });

    test('and is never mistaken for a parent invite code', () {
      for (final r in [withChannel, withCampaign, bare]) {
        expect(InstallReferrerService.codeFromReferrer(r), isNull, reason: r);
      }
    });

    test('the channel comes through', () {
      expect(InstallReferrerService.partnerChannelFromReferrer(withChannel),
          ReferralChannel.qr);
      expect(InstallReferrerService.partnerChannelFromReferrer(withCampaign),
          ReferralChannel.whatsapp);
    });

    test('the campaign comes through', () {
      expect(InstallReferrerService.partnerCampaignFromReferrer(withCampaign),
          'diwali');
      expect(InstallReferrerService.partnerCampaignFromReferrer(withChannel),
          isNull);
    });
  });

  group('invite referrers, exactly as the website emits them', () {
    const invite =
        'utm_source=invite&utm_medium=referral&utm_content=ABCD234';

    test('the code comes through', () {
      expect(InstallReferrerService.codeFromReferrer(invite), 'ABCD234');
    });

    test('and is never mistaken for a partner token', () {
      expect(InstallReferrerService.partnerTokenFromReferrer(invite), isNull);
    });
  });

  group('the two code spaces cannot collide', () {
    test('a 7-char invite code is not a well-formed care token', () {
      expect(CarePartnerEngine.isWellFormed('ABCD234'), isFalse);
    });

    test('a 10-char care token is not a well-formed invite code', () {
      expect(ReferralEngine.isWellFormed('KM7QX2PDVR'), isFalse);
    });

    test('the two engines agree on the alphabet, and differ only in length',
        () {
      expect(CarePartnerEngine.alphabet, ReferralEngine.alphabet);
      expect(CarePartnerEngine.tokenLength, isNot(ReferralEngine.codeLength));
    });

    test('the shared alphabet excludes every character that gets mistyped '
        'off a printed poster', () {
      for (final c in ['I', 'L', 'O', '0', '1']) {
        expect(CarePartnerEngine.alphabet.contains(c), isFalse, reason: c);
      }
    });
  });

  group('the website validators match the app generators', () {
    // These mirror the regexes in C:\parentveda-web\src\lib\{care,invite}.ts.
    // If a generator here ever produces something those reject, real links 404.
    final careRe = RegExp('^[${CarePartnerEngine.alphabet}]'
        '{${CarePartnerEngine.tokenLength}}\$');
    final inviteRe = RegExp('^[${ReferralEngine.alphabet}]'
        '{${ReferralEngine.codeLength}}\$');

    test('every generated care token passes the website regex', () {
      for (var i = 0; i < 200; i++) {
        final t = CarePartnerEngine.tokenFor('partner_$i');
        expect(careRe.hasMatch(t), isTrue, reason: t);
      }
    });

    test('every generated invite code passes the website regex', () {
      for (var i = 0; i < 200; i++) {
        final c = ReferralEngine.codeForUser('user_$i');
        expect(inviteRe.hasMatch(c), isTrue, reason: c);
      }
    });

    test('neither regex accepts the other system\'s output', () {
      final token = CarePartnerEngine.tokenFor('partner_1');
      final code = ReferralEngine.codeForUser('user_1');
      expect(inviteRe.hasMatch(token), isFalse);
      expect(careRe.hasMatch(code), isFalse);
    });
  });

  group('link round-trip through the site URL shape', () {
    test('a /care/ URL the kit builds parses back to the same token', () {
      const token = 'KM7QX2PDVR';
      final url = CarePartnerEngine.linkFor(token,
          channel: ReferralChannel.whatsapp, campaignId: 'diwali');
      final uri = Uri.parse(url);
      expect(uri.host, 'parentveda.in');
      expect(uri.pathSegments.first, 'care');
      expect(CarePartnerEngine.tokenFromUri(uri), token);
      expect(CarePartnerEngine.channelFromUri(uri), ReferralChannel.whatsapp);
      expect(CarePartnerEngine.campaignFromUri(uri), 'diwali');
    });

    test('a lowercased /care/ URL still resolves — chat apps lowercase the '
        'tail of an auto-linked URL', () {
      final uri = Uri.parse('https://parentveda.in/care/km7qx2pdvr?ch=qr');
      expect(CarePartnerEngine.tokenFromUri(uri), 'KM7QX2PDVR');
    });

    test('an /invite/ URL never resolves as a care token', () {
      final uri = Uri.parse('https://parentveda.in/invite/ABCD234');
      expect(CarePartnerEngine.tokenFromUri(uri), isNull);
    });
  });
}
