// =============================================================================
//  Every narration key used in the app must exist in the manifest
// -----------------------------------------------------------------------------
//  A wrong key is not a crash. NarrationService falls back to the device voice,
//  so a typo in `week20.babySnapsot.reveal` produces a working button that
//  quietly never plays the recording - for that passage, forever. Nobody would
//  notice except a mother wondering why one card sounds different.
//
//  That is the same class of failure as the wiring gate this repo already
//  guards: correct-looking code that is simply never reached. So the keys are
//  checked against the generated manifest rather than trusted.
//
//  The manifest is regenerated by tool/generate_audio.py; the STAGED one under
//  assets/ may hold a subset while audio is local, so this checks the full
//  build manifest when it exists and falls back to the staged one.
// =============================================================================

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// `NarrationService.weekKey(20, 'babySnapshot.reveal')` and any literal key.
final _weekKeyCall = RegExp(
    r"""weekKey\(\s*(\w+)\s*,\s*'([^']+)'""");
final _literalKey = RegExp(
    r"""narrationKey:\s*'([^']+)'""");

Map<String, dynamic> _manifest() {
  for (final path in [
    'build/audio/manifest_hi.json',
    'assets/narration/manifest_hi.json',
  ]) {
    final f = File(path);
    if (f.existsSync()) {
      return jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    }
  }
  return const {};
}

void main() {
  test('every narration path used in the app exists in the manifest', () {
    final manifest = _manifest();
    if (manifest.isEmpty) {
      // Generated output is gitignored, so a clean checkout has no manifest.
      // Skipping is honest; failing would make the suite depend on a build
      // step nobody ran.
      return;
    }

    // The set of `<field path>` suffixes the manifest knows about, per week.
    final knownPaths = <String>{};
    for (final key in manifest.keys) {
      final dot = key.indexOf('.');
      if (dot > 0) knownPaths.add(key.substring(dot + 1));
    }

    final offenders = <String>[];
    for (final file in Directory('lib')
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'))) {
      final src = file.readAsStringSync();
      for (final m in _weekKeyCall.allMatches(src)) {
        final path = m.group(2)!;
        if (!knownPaths.contains(path)) {
          offenders.add('${file.path}: weekKey path "$path"');
        }
      }
      for (final m in _literalKey.allMatches(src)) {
        final key = m.group(1)!;
        if (!key.contains(r'$') && !manifest.containsKey(key)) {
          offenders.add('${file.path}: key "$key"');
        }
      }
    }

    expect(offenders, isEmpty,
        reason: 'These keys have no audio and will silently fall back to the '
            'device voice forever:\n${offenders.join('\n')}');
  });
}
