// =============================================================================
//  TTC practice cue sounds — a soft tone when something counts or times
// -----------------------------------------------------------------------------
//  The user, 2026-09-28, on build 17: "wherever in the trying to conceive side
//  there is anything that indicates a sound, a countdown or something that
//  indicates a sound, have a sound." Until now every TTC timer was silent: a
//  breathing practice done with eyes closed meant opening them to see whether
//  the circle had turned, and a two-minute sit ended without a word.
//
//  Five cues, generated by tools/gen_ttc_cue_sounds.py (soft sine tones between
//  about 300 and 900 Hz, faded in and out, under 60 KB each):
//
//    breathe_in   a tone rising G4 to C5     as an in-breath begins
//    hold         one level, quieter A4      as a hold (full or empty) begins
//    breathe_out  a tone falling C5 to G4    as an out-breath begins
//    step         one soft tap of D5         as a timed step changes
//    done         two bell notes, G4 then C5 when a practice or timer ends
//
//  WHO CALLS IT: only `TtcPracticeSessionState` in
//  lib/screens/ttc/ttc_practice_player.dart. Every TTC countdown is that one
//  session (the practice page, the Sanskar breath, the course sits and course
//  practices), so one call site covers the stage. The shared
//  `PvBreathingCircle` is not touched: it only draws, and pregnancy, parenting
//  and skilling use it too.
//
//  ⚠️ THE AUDIO CONTEXT, AND WHY (the trade-off, for the learning doc):
//  A sound cue is a UI sound, not media. Two things follow.
//   · It must NOT take audio focus. Media playback asks for focus, and the
//     OS then pauses whatever else was playing. The listening practice says
//     "Play your own music"; a cue that paused her music every breath would
//     break the practice it is meant to help. So Android asks for no focus
//     (`AndroidAudioFocus.none`) and iOS uses the `ambient` category, which
//     mixes with other audio by definition.
//   · It should obey the phone's quiet settings. Android's
//     `assistanceSonification` usage is the one for "a sound that accompanies
//     an interface event"; it plays on the system stream, which silent and
//     vibrate mode mute and Do Not Disturb holds back unless system sounds are
//     allowed. iOS `ambient` is silenced by the Ring/Silent switch.
//  The cost: the cue follows the phone's System volume (Android), not the
//  media volume, so a phone with system sounds turned right down hears it
//  faintly. The alternative, `notification` usage, is louder on most phones
//  but reads as "a message arrived", which is the wrong meaning mid-breath.
//
//  ⚠️ LOW-LATENCY MODE. `PlayerMode.lowLatency` is Android's SoundPool: the
//  sound is decoded once into memory and starts within a frame or two. The
//  default MediaPlayer mode prepares the file on every play, which puts
//  50-200 ms between the circle turning and the tone, enough to feel wrong on
//  a four-second breath. SoundPool cannot seek or report completion, which
//  cues never need.
//
//  ⚠️ NEVER A CRASH, AND SILENT IN TESTS. Every platform call is wrapped, and
//  a failure is swallowed: a missing tone is a lesser loss than a practice
//  that stops. Under `flutter test` there is no audio plugin, so no player is
//  made at all unless a test injects a fake through [TtcCueSounds.playerFactory].
// =============================================================================

import 'dart:async';
import 'dart:io' show Platform;

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../models/breath_pattern.dart' show BreathKind;

/// The five cues.
enum TtcCue {
  breatheIn('breathe_in.wav'),
  hold('hold.wav'),
  breatheOut('breathe_out.wav'),
  step('step.wav'),
  done('done.wav');

  const TtcCue(this.file);

  /// The file under assets/audio/cues/.
  final String file;

  /// The path `AssetSource` takes (relative to assets/).
  String get assetSource => 'audio/cues/$file';

  /// The path on disk and in pubspec.yaml.
  String get assetPath => 'assets/audio/cues/$file';
}

/// The cue for the start of a breath phase. A hold after the out-breath takes
/// the same tone as a hold after the in-breath: both are "pause here".
TtcCue ttcCueForBreath(BreathKind kind) => switch (kind) {
      BreathKind.expand => TtcCue.breatheIn,
      BreathKind.hold => TtcCue.hold,
      BreathKind.contract => TtcCue.breatheOut,
      BreathKind.holdEmpty => TtcCue.hold,
    };

/// What actually makes the sound. The app's is [_AudioplayersCuePlayer]; a
/// test passes a fake that records what it was asked to play.
abstract interface class TtcCuePlayer {
  Future<void> preload();
  Future<void> play(TtcCue cue);
  Future<void> dispose();
}

/// The switch and the player, one per app.
class TtcCueSounds extends ChangeNotifier {
  TtcCueSounds._();
  static final TtcCueSounds instance = TtcCueSounds._();

  static const String prefsKey = 'ttc_practice_sound';

  /// A test's fake player. Null in the app.
  @visibleForTesting
  TtcCuePlayer Function()? playerFactory;

  bool _enabled = true;
  bool _loaded = false;
  TtcCuePlayer? _player;
  int _holders = 0;

  /// Whether cues play. ON by default (the user asked for sound), remembered
  /// on this phone. The phone's own silent mode still wins; see the header.
  bool get enabled {
    _load();
    return _enabled;
  }

  void _load() {
    if (_loaded) return;
    _loaded = true;
    SharedPreferences.getInstance().then((p) {
      final v = p.getBool(prefsKey);
      if (v != null && v != _enabled) {
        _enabled = v;
        notifyListeners();
      }
    }).catchError((Object _) {});
  }

  /// Turns the cues on or off, and remembers it.
  void setEnabled(bool on) {
    _loaded = true;
    if (_enabled != on) {
      _enabled = on;
      notifyListeners();
    }
    SharedPreferences.getInstance()
        .then((p) => p.setBool(prefsKey, on))
        .catchError((Object _) => false);
    // A sample, so she hears what she just turned on.
    if (on) play(TtcCue.step);
  }

  /// A session on screen asks for the player. The first one loads the five
  /// tones; later ones share them.
  ///
  /// ⚠️ COUNTED, BECAUSE A PAGE CAN HOLD SEVERAL SESSIONS. A course session
  /// draws a sit and two practices; closing one of them must not unload the
  /// tones the other two still need.
  void open() {
    _load();
    _holders++;
    if (_player != null) return;
    final p = _make();
    if (p == null) return;
    _player = p;
    _guard(p.preload);
  }

  /// A session leaves the screen. The last one out releases the players.
  void close() {
    if (_holders > 0) _holders--;
    if (_holders > 0) return;
    final p = _player;
    _player = null;
    if (p != null) _guard(p.dispose);
  }

  /// Plays one cue, if cues are on and a session has opened the player.
  /// Never throws and never waits.
  void play(TtcCue cue) {
    if (!_enabled) return;
    final p = _player;
    if (p == null) return;
    _guard(() => p.play(cue));
  }

  static void _guard(Future<void> Function() f) {
    try {
      f().catchError((Object _) {});
    } catch (_) {}
  }

  TtcCuePlayer? _make() {
    if (playerFactory case final make?) {
      try {
        return make();
      } catch (_) {
        return null;
      }
    }
    if (_underTest) return null;
    return _AudioplayersCuePlayer();
  }

  /// `flutter test` sets FLUTTER_TEST; there is no audio plugin there.
  static bool get _underTest {
    if (kIsWeb) return false;
    try {
      return Platform.environment.containsKey('FLUTTER_TEST');
    } catch (_) {
      return true;
    }
  }

  /// Whether a player is loaded now. For a test.
  @visibleForTesting
  bool get hasPlayer => _player != null;

  @visibleForTesting
  int get holders => _holders;

  @visibleForTesting
  void resetForTest() {
    final p = _player;
    _player = null;
    if (p != null) _guard(p.dispose);
    _holders = 0;
    _enabled = true;
    _loaded = false;
    playerFactory = null;
  }
}

/// The real thing: one low-latency `AudioPlayer` per cue, so two cues close
/// together (a step and the end) never cut each other off.
class _AudioplayersCuePlayer implements TtcCuePlayer {
  final Map<TtcCue, AudioPlayer> _players = {};
  Future<void>? _ready;

  /// Quieter than the file, which already peaks near -10 dBFS: a cue sits
  /// under the practice, never over it.
  static const double _volume = 0.7;

  static final AudioContext _context = AudioContext(
    android: const AudioContextAndroid(
      isSpeakerphoneOn: false,
      stayAwake: false,
      contentType: AndroidContentType.sonification,
      usageType: AndroidUsageType.assistanceSonification,
      audioFocus: AndroidAudioFocus.none,
    ),
    // `ambient` mixes with other audio already; `mixWithOthers` may only be
    // set explicitly on playback-type categories (the plugin asserts it).
    iOS: AudioContextIOS(
      category: AVAudioSessionCategory.ambient,
      options: const {},
    ),
  );

  @override
  Future<void> preload() => _ready ??= _load();

  Future<void> _load() async {
    for (final cue in TtcCue.values) {
      final p = AudioPlayer();
      _players[cue] = p;
      try {
        // The context first: SoundPool is created for the context it is
        // given, so setting it after the mode would build a second pool.
        await p.setAudioContext(_context);
        await p.setPlayerMode(PlayerMode.lowLatency);
        await p.setReleaseMode(ReleaseMode.stop);
        await p.setVolume(_volume);
        await p.setSource(AssetSource(cue.assetSource));
      } catch (_) {}
    }
  }

  @override
  Future<void> play(TtcCue cue) async {
    await preload();
    final p = _players[cue];
    if (p == null) return;
    // ⚠️ STOP, THEN RESUME. SoundPool never reports that a sound finished,
    // so the plugin still thinks the last play is running and ignores a
    // second resume. Stop rewinds it; resume plays from the top.
    await p.stop();
    await p.resume();
  }

  @override
  Future<void> dispose() async {
    final all = _players.values.toList();
    _players.clear();
    for (final p in all) {
      try {
        await p.dispose();
      } catch (_) {}
    }
  }
}
