// =============================================================================
//  TtcJournalStore - the shared journal of the TTC stage
// -----------------------------------------------------------------------------
//  Why this is not the pregnancy JournalStore, despite "one brain, two doors":
//  that store derives a pregnancy WEEK for every entry from PregnancyController
//  (`_weekAt`). Reusing it would either drag the pregnancy controller into a
//  stage that has no due date, or record every TTC memory against a week that
//  does not exist yet.
//
//  So the entries live here, and Phase 7's Transition Engine carries them
//  FORWARD into the continuous timeline rather than leaving them behind. The
//  master document is explicit that nothing may be lost at the transition
//  (§3.15: "Everything survives into Pregnancy"), and the shape below is built
//  for that: app-generated ids, an author, and an absolute date rather than a
//  stage-relative one.
//
//  The author field exists from day one because this is a TWO-PERSON journal -
//  §3.15 - even though the partner side is not built until Phase 5. Adding it
//  later would mean migrating every existing entry.
// =============================================================================

import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../services/remote/supabase_repo.dart';
import 'ttc_sync.dart';

/// Who wrote it. Entries are attributed, never hidden from each other - unlike
/// baby-name votes, there is no reason for a shared journal to keep secrets.
enum TtcAuthor { me, partner }

/// What kind of entry it is. Deliberately small - a journal with fifteen
/// categories is a form, not a journal.
enum TtcEntryKind { memory, letter, question, feeling }

extension TtcEntryKindCopy on TtcEntryKind {
  String label(bool hi) {
    switch (this) {
      case TtcEntryKind.memory:
        return hi ? 'Yaad' : 'A memory';
      case TtcEntryKind.letter:
        return hi ? 'Bachche ke naam' : 'To our child';
      case TtcEntryKind.question:
        return hi ? 'Doctor ke liye sawaal' : 'For the doctor';
      case TtcEntryKind.feeling:
        return hi ? 'Aaj kaisa laga' : 'How today felt';
    }
  }

  String get icon => name; // resolved to an IconData at the call site
}

class TtcJournalEntry {
  const TtcJournalEntry({
    required this.id,
    required this.dateIso,
    required this.kind,
    required this.text,
    this.author = TtcAuthor.me,
    this.prompt,
    this.photoPath,
  });

  /// Generated by the app so a local row and its cloud copy share one identity
  /// and syncing stays an idempotent merge. (House rule.)
  final String id;
  final String dateIso;
  final TtcEntryKind kind;
  final String text;
  final TtcAuthor author;

  /// The prompt this was written against, if any - kept so the entry still
  /// makes sense years later when the prompt has long rotated away.
  final String? prompt;
  final String? photoPath;

  DateTime get date => DateTime.tryParse(dateIso) ?? DateTime.now();

  // JSON rather than a delimiter. A journal entry is free text - it can contain
  // any character a phone keyboard produces, including whatever separator we
  // might have picked - and quietly corrupting somebody's letter to their
  // future child is not an acceptable failure mode.
  String encode() => jsonEncode({
        'id': id,
        'date': dateIso,
        'kind': kind.name,
        'author': author.name,
        if (prompt != null) 'prompt': prompt,
        if (photoPath != null) 'photo': photoPath,
        'text': text,
      });

  static TtcJournalEntry? decode(String raw) {
    try {
      final m = jsonDecode(raw);
      if (m is! Map) return null;
      final id = m['id'];
      final date = m['date'];
      if (id is! String || date is! String) return null;
      return TtcJournalEntry(
        id: id,
        dateIso: date,
        kind:
            TtcEntryKind.values.where((e) => e.name == m['kind']).firstOrNull ??
                TtcEntryKind.memory,
        author:
            TtcAuthor.values.where((e) => e.name == m['author']).firstOrNull ??
                TtcAuthor.me,
        prompt: m['prompt'] as String?,
        photoPath: m['photo'] as String?,
        text: (m['text'] as String?) ?? '',
      );
    } catch (_) {
      // A corrupt row is dropped, never allowed to take the whole journal down.
      return null;
    }
  }
}

class TtcJournalStore extends ChangeNotifier with TtcSyncedStore {
  TtcJournalStore._() {
    _load();
  }
  static final TtcJournalStore instance = TtcJournalStore._();

  static const _key = 'ttc_journal';

  final List<TtcJournalEntry> _entries = [];
  bool _loaded = false;

  bool get isLoaded => _loaded;

  /// Newest first - the order a journal is actually read in.
  List<TtcJournalEntry> get entries {
    final out = [..._entries];
    out.sort((a, b) => b.dateIso.compareTo(a.dateIso));
    return List.unmodifiable(out);
  }

  int get count => _entries.length;

  List<TtcJournalEntry> ofKind(TtcEntryKind kind) =>
      entries.where((e) => e.kind == kind).toList();

  /// Questions saved for the doctor - read by the appointment companion later.
  List<TtcJournalEntry> get doctorQuestions => ofKind(TtcEntryKind.question);

  TtcJournalEntry add({
    required TtcEntryKind kind,
    required String text,
    TtcAuthor author = TtcAuthor.me,
    String? prompt,
    String? photoPath,
    DateTime? on,
  }) {
    final now = on ?? DateTime.now();
    final entry = TtcJournalEntry(
      id: 'ttcj_${now.microsecondsSinceEpoch}',
      dateIso: now.toIso8601String(),
      kind: kind,
      text: text.trim(),
      author: author,
      prompt: prompt,
      photoPath: photoPath,
    );
    _entries.add(entry);
    _persist();
    notifyListeners();
    return entry;
  }

  /// Changes the words of an entry THIS person wrote (tools pass, 2026-09-27).
  ///
  /// Only her own: a partner's entry is his to change, and the cloud refuses a
  /// forged author anyway (0041). The id and the written date stay the same,
  /// so the edit is an upsert of the same row on the next push, never a second
  /// entry. An empty edit is refused rather than saved: clearing the words is
  /// not how a letter to a child should be deleted, and Delete has its own
  /// confirm. Returns whether anything changed.
  ///
  /// [kind] is optional and additive (2026-09-27, tools rebuild): she can move
  /// an entry she filed under the wrong kind, the way Day One lets any part of
  /// an entry be changed. `kind` is already a synced column, so no schema
  /// change rides on it.
  bool update(String id, {required String text, TtcEntryKind? kind}) {
    final i = _entries.indexWhere((e) => e.id == id);
    if (i < 0) return false;
    final old = _entries[i];
    final next = text.trim();
    final nextKind = kind ?? old.kind;
    if (old.author != TtcAuthor.me ||
        next.isEmpty ||
        (next == old.text && nextKind == old.kind)) {
      return false;
    }
    _entries[i] = TtcJournalEntry(
      id: old.id,
      dateIso: old.dateIso,
      kind: nextKind,
      text: next,
      author: old.author,
      prompt: old.prompt,
      photoPath: old.photoPath,
    );
    _persist();
    notifyListeners();
    return true;
  }

  /// Puts back an entry she has just deleted, same id and date (the Undo on
  /// "Entry deleted", 2026-09-27). The cloud delete has already gone out, so
  /// the row is re-sent by the debounced push that `notifyListeners` starts,
  /// as an upsert of the same id: the app-generated id is what makes this
  /// safe, a restore can never become a second copy.
  void restore(TtcJournalEntry entry) {
    if (_entries.any((e) => e.id == entry.id)) return;
    _entries.add(entry);
    _persist();
    notifyListeners();
  }

  void remove(String id) {
    final before = _entries.length;
    _entries.removeWhere((e) => e.id == id);
    if (_entries.length == before) return;
    _persist();
    // Explicit, because the merge is a union - otherwise the deleted entry
    // reappears on the next pull.
    if (SupabaseRepo.isLoggedIn) {
      SupabaseRepo.delete(TtcTables.journal, id).catchError((_) {});
    }
    notifyListeners();
  }

  @visibleForTesting
  void resetForTest() {
    _entries.clear();
    _loaded = true;
    notifyListeners();
  }

  Future<void> _load() async {
    if (_loaded) return;
    try {
      final p = await SharedPreferences.getInstance();
      _entries
        ..clear()
        ..addAll((p.getStringList(_key) ?? const <String>[])
            .map(TtcJournalEntry.decode)
            .whereType<TtcJournalEntry>());
    } catch (_) {/* keep defaults */}
    _loaded = true;
    notifyListeners();
    await syncFromCloud();
  }

  // ---- cloud ----------------------------------------------------------------
  //  COUPLE-SCOPED, both directions: seeing what your partner wrote is the
  //  feature. `fetchShared` lets RLS return both people's rows.
  //
  //  Union-merge only. Cloud-wins would silently delete an entry written on a
  //  plane the moment the phone reconnected, and this is the one store where
  //  that would destroy something irreplaceable.

  @override
  Future<void> pullFromCloud() async {
    final rows = await SupabaseRepo.fetchShared(TtcTables.journal,
        orderBy: 'written_at', ascending: true);
    for (final row in rows) {
      final id = row['id'];
      if (id is! String) continue;
      // ⚠️ EACH ENTRY IS OWNED BY ITS AUTHOR (2026-09-27, when edit arrived).
      // Her own rows: the local copy wins, so an edit made offline is never
      // overwritten by the older cloud text. His rows: the cloud wins, so an
      // edit he makes on his phone reaches hers. Before edit existed, "skip
      // what we already have" was enough; with edit it would freeze his words
      // at whatever they said the first time her phone saw them.
      final have = _entries.indexWhere((e) => e.id == id);
      if (have >= 0) {
        final local = _entries[have];
        final body = row['body'] as String?;
        if (local.author == TtcAuthor.partner &&
            body != null &&
            body.isNotEmpty &&
            body != local.text) {
          _entries[have] = TtcJournalEntry(
            id: local.id,
            dateIso: local.dateIso,
            kind: local.kind,
            text: body,
            author: local.author,
            prompt: local.prompt,
            photoPath: local.photoPath,
          );
        }
        continue;
      }
      _entries.add(TtcJournalEntry(
        id: id,
        dateIso: SupabaseRepo.parseDbTime(row['written_at']).toIso8601String(),
        kind: TtcEntryKind.values
                .where((e) => e.name == row['kind'])
                .firstOrNull ??
            TtcEntryKind.memory,
        // Whose entry it is comes from author_id vs the signed-in user, not
        // from a flag the writing client chose.
        author: row['author_id'] == SupabaseRepo.userId
            ? TtcAuthor.me
            : TtcAuthor.partner,
        text: (row['body'] as String?) ?? '',
        prompt: row['prompt'] as String?,
        photoPath: row['photo_path'] as String?,
      ));
    }
  }

  @override
  Future<void> pushToCloud() async {
    final uid = SupabaseRepo.userId;
    if (uid == null) return;
    await TtcSyncUtil.upsertAll(
      TtcTables.journal,
      [
        // Only push what THIS user wrote. The partner's entries arrived from
        // the cloud and are theirs to own - and 0041 refuses a forged author
        // anyway.
        for (final e in _entries.where((e) => e.author == TtcAuthor.me))
          {
            'id': e.id,
            'user_id': uid,
            'author_id': uid,
            'kind': e.kind.name,
            'body': e.text,
            if (e.prompt != null) 'prompt': e.prompt,
            if (e.photoPath != null) 'photo_path': e.photoPath,
            'written_at': SupabaseRepo.dbTime(e.date),
          }
      ],
      onConflict: 'id',
    );
  }

  @override
  Future<void> persistLocalCache() => _persist();

  Future<void> _persist() async {
    try {
      final p = await SharedPreferences.getInstance();
      await p.setStringList(_key, _entries.map((e) => e.encode()).toList());
    } catch (_) {/* best-effort */}
  }
}
