// =============================================================================
//  SEED GENERATOR (not a test) — turn bundled Dart content into seed SQL.
// -----------------------------------------------------------------------------
//  Run:  flutter test tool/export_content_seed.dart
//  Out:  build/seed_recipes.sql   (and one file per type as more are flipped)
//
//  Why generate rather than hand-write: step 3 of the add-a-type recipe says the
//  seed must make day one look IDENTICAL to the bundled app. Transcribing 28
//  dishes × 30 fields by hand is how a dropped ingredient or a swapped step
//  gets into the database — a difference nobody reviews, because nobody
//  re-reads a 900-line INSERT. Generating it means the only thing that can
//  drift is this file, and test/recipes_seed_test.dart watches that.
//
//  Every statement is `on conflict (source_key) do nothing`, so running the
//  output twice is a no-op and it can NEVER overwrite an editor's edit. That
//  property is what makes a flip reversible: seed, ship, and if it goes wrong,
//  flip ContentOwnership back without having lost anything.
//
//  It lives in tool/ and runs via `flutter test` for the same reason the corpus
//  exporters do — the data pulls in Flutter (IconData/Color), so `dart run`
//  cannot load it, and keeping it out of test/ means it never runs in the suite.
// =============================================================================

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:parentveda/screens/post_pregnancy/pp_food_data.dart';
import 'package:parentveda/screens/post_pregnancy/pp_products_data.dart';
import 'package:parentveda/screens/post_pregnancy/pp_reading_data.dart';

// ---- SQL literal helpers ----------------------------------------------------

/// A quoted SQL string, or NULL. Single quotes are doubled — the standard
/// escape, and the only one that is safe regardless of what the prose contains.
/// Deliberately NOT dollar-quoting: content is authored by humans and a `$$`
/// inside a note would end the literal early and produce a syntax error at the
/// worst possible moment (halfway through a 900-line insert).
String _s(String? v) {
  if (v == null) return 'null';
  return "'${v.replaceAll("'", "''")}'";
}

String _b(bool v) => v ? 'true' : 'false';

/// A nullable boolean. The compare specs are three-valued on purpose — "this
/// product has no auto-off" and "we have not checked" are different claims to
/// make about something a parent is choosing between, so null must survive
/// rather than collapsing to false.
String _nb(bool? v) => v == null ? 'null' : _b(v);

/// A Postgres text[] built explicitly rather than via '{a,b}' syntax, which
/// needs its own escaping rules for commas, braces and quotes.
String _arr(Iterable<String> items) {
  if (items.isEmpty) return "'{}'::text[]";
  return 'array[${items.map(_s).join(', ')}]::text[]';
}

String _json(Object? value) => "${_s(jsonEncode(value))}::jsonb";

/// Split an age tag like '6–12 mo' / '1-3 yr' into filterable months.
/// Returns (min, max); either may be null when the tag does not say.
(int?, int?) _ageMonths(String tag) {
  final t = tag.toLowerCase().replaceAll('–', '-').replaceAll('+', '');
  final nums = RegExp(r'\d+')
      .allMatches(t)
      .map((m) => int.parse(m.group(0)!))
      .toList();
  if (nums.isEmpty) return (null, null);
  final isYears = t.contains('yr') || t.contains('year');
  final scale = isYears ? 12 : 1;
  final lo = nums.first * scale;
  final hi = nums.length > 1 ? nums[1] * scale : null;
  return (lo, hi);
}

void main() {
  test('generate build/seed_recipes.sql from kFoodRecipes', () {
    final buf = StringBuffer()
      ..writeln('-- GENERATED by tool/export_content_seed.dart — do not edit by hand.')
      ..writeln('-- Source: lib/screens/post_pregnancy/pp_food_data.dart (kFoodRecipes)')
      ..writeln('-- Safe to re-run: on conflict (source_key) do nothing.')
      ..writeln('--')
      ..writeln('-- This makes the recipes table match what the app already ships, so')
      ..writeln('-- switching RecipeStore to the database changes nothing visible. That')
      ..writeln('-- is the point — a flip you cannot see is a flip you can trust.')
      ..writeln();

    for (var i = 0; i < kFoodRecipes.length; i++) {
      final r = kFoodRecipes[i];
      final (ageMin, ageMax) = _ageMonths(r.ageTag);

      buf
        ..writeln('insert into public.recipes (')
        ..writeln('  source_key, status, domain, title, subtitle, category, slot,')
        ..writeln('  age_tag, age_min_months, age_max_months,')
        ..writeln('  veg, vegan, immunity, comfort_only,')
        ..writeln('  prep_min, cook_min, serves, difficulty, frequency,')
        ..writeln('  highlight, why, healthier_note,')
        ..writeln('  ingredients, equipment, steps, storage, mistakes,')
        ..writeln('  substitutions, nutrients,')
        ..writeln('  tags, situations, ingredient_keys,')
        ..writeln('  related_article, related_video_id, related_product_id, related_community,')
        ..writeln('  shuffle_seed, sort')
        ..writeln(') values (')
        ..writeln('  ${_s(r.id)}, \'published\', \'parenting\', ${_s(r.title)}, ${_s(r.subtitle)}, ${_s(r.category)}, ${_s(r.slot)},')
        ..writeln('  ${_s(r.ageTag)}, ${ageMin ?? 'null'}, ${ageMax ?? 'null'},')
        ..writeln('  ${_b(r.veg)}, ${_b(r.vegan)}, ${_b(r.immunity)}, ${_b(r.comfortOnly)},')
        ..writeln('  ${r.prepMin}, ${r.cookMin}, ${r.serves}, ${_s(r.difficulty)}, ${_s(r.frequency)},')
        ..writeln('  ${_s(r.highlight)}, ${_s(r.why)}, ${_s(r.healthierNote)},')
        ..writeln('  ${_json(r.ingredients)}, ${_json(r.equipment)}, ${_json(r.steps)}, ${_json(r.storage)}, ${_json(r.mistakes)},')
        ..writeln('  ${_json(r.substitutions)},')
        ..writeln('  ${_json(r.nutrients.map((n) => {'name': n.name, 'amount': n.amount, 'note': n.note}).toList())},')
        ..writeln('  ${_arr(r.tags)}, ${_arr(r.situations)}, ${_arr(r.ingredientKeys)},')
        ..writeln('  ${_s(r.relatedArticle)}, ${_s(r.relatedVideoId)}, ${_s(r.relatedProductId)}, ${_s(r.relatedCommunity)},')
        ..writeln('  ${r.seed}, $i')
        ..writeln(') on conflict (source_key) do nothing;')
        ..writeln();
    }

    buf
      ..writeln('-- Sanity check after running this file:')
      ..writeln('--   select count(*) from public.recipes;   -- expect ${kFoodRecipes.length}');

    final f = File('build/seed_recipes.sql');
    f.parent.createSync(recursive: true);
    f.writeAsStringSync(buf.toString());

    // ignore: avoid_print
    print('\nGENERATED ${kFoodRecipes.length} recipes -> build/seed_recipes.sql');

    expect(kFoodRecipes, isNotEmpty);
  });

  test('generate build/seed_reads.sql from kReadArticles', () {
    final buf = StringBuffer()
      ..writeln('-- GENERATED by tool/export_content_seed.dart — do not edit by hand.')
      ..writeln('-- Source: lib/screens/post_pregnancy/pp_reading_data.dart (kReadArticles)')
      ..writeln('-- Safe to re-run: on conflict (source_key) do nothing.')
      ..writeln();

    for (var i = 0; i < kReadArticles.length; i++) {
      final a = kReadArticles[i];
      final (ageMin, ageMax) = _ageMonths(a.ageTag);

      // The reader's blocks, flattened to the jsonb shape ReadStore decodes.
      // Optional inline elements are omitted rather than written as null, so
      // the stored JSON reads the way an editor would write it.
      final sections = a.sections
          .map((s) => <String, dynamic>{
                if (s.heading != null) 'heading': s.heading,
                'paragraphs': s.paragraphs,
                if (s.tip != null)
                  'tip': {'title': s.tip!.title, 'body': s.tip!.body},
                if (s.mythFact != null)
                  'mythFact': {
                    'myth': s.mythFact!.myth,
                    'fact': s.mythFact!.fact,
                  },
                if (s.image) 'image': true,
              })
          .toList();

      buf
        ..writeln('insert into public.reads (')
        ..writeln('  source_key, status, domain, title, teaser, why_today,')
        ..writeln('  collection, kind, age_tag, age_min_months, age_max_months, minutes,')
        ..writeln('  author, author_role, evidence, sections,')
        ..writeln('  related_activity, related_video_id, related_video_ids,')
        ..writeln('  related_recipe_id, related_product_id, related_community,')
        ..writeln('  shuffle_seed, sort')
        ..writeln(') values (')
        ..writeln('  ${_s(a.id)}, \'published\', \'parenting\', ${_s(a.title)}, ${_s(a.teaser)}, ${_s(a.whyToday)},')
        ..writeln('  ${_s(a.collection)}, ${_s(a.kind.name)}, ${_s(a.ageTag)}, ${ageMin ?? 'null'}, ${ageMax ?? 'null'}, ${a.minutes},')
        ..writeln('  ${_s(a.author)}, ${_s(a.authorRole)}, ${_s(a.evidence)}, ${_json(sections)},')
        ..writeln('  ${_s(a.relatedActivity)}, ${_s(a.relatedVideoId)}, ${_arr(a.relatedVideoIds)},')
        ..writeln('  ${_s(a.relatedRecipeId)}, ${_s(a.relatedProductId)}, ${_s(a.relatedCommunity)},')
        ..writeln('  ${a.seed}, $i')
        ..writeln(') on conflict (source_key) do nothing;')
        ..writeln();
    }

    buf
      ..writeln('-- Sanity check after running this file:')
      ..writeln('--   select count(*) from public.reads;   -- expect ${kReadArticles.length}');

    final f = File('build/seed_reads.sql');
    f.parent.createSync(recursive: true);
    f.writeAsStringSync(buf.toString());

    // ignore: avoid_print
    print('GENERATED ${kReadArticles.length} reads -> build/seed_reads.sql');

    expect(kReadArticles, isNotEmpty);
  });

  test('generate build/seed_products.sql from kPpProducts', () {
    final buf = StringBuffer()
      ..writeln('-- GENERATED by tool/export_content_seed.dart — do not edit by hand.')
      ..writeln('-- Source: lib/screens/post_pregnancy/pp_products_data.dart (kPpProducts)')
      ..writeln('-- Safe to re-run: on conflict (source_key) do nothing.')
      ..writeln('--')
      ..writeln('-- price_inr is WHOLE RUPEES, matching the bundled Dart exactly.')
      ..writeln();

    for (var i = 0; i < kPpProducts.length; i++) {
      final p = kPpProducts[i];
      buf
        ..writeln('insert into public.products (')
        ..writeln('  source_key, status, domain, name, brand, category, sub,')
        ..writeln('  price_inr, retailer, rating, reviews,')
        ..writeln('  verified, parent_veda, bestseller, badge, best_for, summary,')
        ..writeln('  pros, cons, specs,')
        ..writeln('  spec_sound, spec_auto_off, spec_volume_lock, spec_power,')
        ..writeln('  sort')
        ..writeln(') values (')
        ..writeln('  ${_s(p.id)}, \'published\', \'parenting\', ${_s(p.name)}, ${_s(p.brand)}, ${_s(p.category)}, ${_s(p.sub)},')
        ..writeln('  ${p.price}, ${_s(p.retailer)}, ${p.rating}, ${p.reviews},')
        ..writeln('  ${_b(p.verified)}, ${_b(p.parentVeda)}, ${_b(p.bestseller)}, ${_s(p.badge)}, ${_s(p.bestFor)}, ${_s(p.summary)},')
        ..writeln('  ${_json(p.pros)}, ${_json(p.cons)}, ${_json(p.specs)},')
        ..writeln('  ${_s(p.sound)}, ${_nb(p.autoOff)}, ${_nb(p.volumeLock)}, ${_s(p.power)},')
        ..writeln('  $i')
        ..writeln(') on conflict (source_key) do nothing;')
        ..writeln();
    }

    buf
      ..writeln('-- Sanity check after running this file:')
      ..writeln('--   select count(*) from public.products;   -- expect ${kPpProducts.length}');

    final f = File('build/seed_products.sql');
    f.parent.createSync(recursive: true);
    f.writeAsStringSync(buf.toString());

    // ignore: avoid_print
    print('GENERATED ${kPpProducts.length} products -> build/seed_products.sql');

    expect(kPpProducts, isNotEmpty);
  });
}
